version: 2.6.0
image: Visual Studio 2022
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
init:
  - net start MSSQL$SQL2019
build_script:
- cmd: build_server.bat
test_script:
- cmd: dotnet test .\src\NEvilES.Tests\NEvilES.Tests.csproj
after_test:
- cmd: dotnet pack .\src\NEvilES\NEvilES.csproj -c Release -o .\artifacts\ /property:version=%APPVEYOR_BUILD_VERSION%
- cmd: dotnet pack .\src\NEvilES.Abstractions\NEvilES.Abstractions.csproj -c Release -o .\artifacts\ /property:version=%APPVEYOR_BUILD_VERSION%
#- cmd: dotnet pack .\src\NEvilES.Extensions.DependencyInjection\NEvilES.Extensions.DependencyInjection.csproj -c Release -o .\artifacts\ /property:version=%APPVEYOR_BUILD_VERSION%
- cmd: dotnet pack .\src\NEvilES.DataStore.SQL\NEvilES.DataStore.SQL.csproj -c Release -o .\artifacts\ /property:version=%APPVEYOR_BUILD_VERSION%
- cmd: dotnet pack .\src\NEvilES.DataStore.Marten\NEvilES.DataStore.Marten.csproj -c Release -o .\artifacts\ /property:version=%APPVEYOR_BUILD_VERSION%
- cmd: dotnet pack .\src\NEvilES.DataStore.DynamoDB\NEvilES.DataStore.DynamoDB.csproj -c Release -o .\artifacts\ /property:version=%APPVEYOR_BUILD_VERSION%
- cmd: dotnet pack .\src\NEvilES.DataStore.LiteDb\NEvilES.DataStore.LiteDb.csproj -c Release -o .\artifacts\ /property:version=%APPVEYOR_BUILD_VERSION%
- cmd: dotnet pack .\src\NEvilES.Testing\NEvilES.Testing.csproj -c Release -o .\artifacts\ /property:version=%APPVEYOR_BUILD_VERSION%
- cmd: dotnet pack .\src\Outbox\Outbox.Abstractions\Outbox.Abstractions.csproj -c Release -o .\artifacts\ /property:version=%APPVEYOR_BUILD_VERSION%
artifacts:
- path: 'artifacts\*.nupkg'
  name: NEvilES

deploy:
- provider: NuGet
  api_key:
    secure: zfWdL/evMCOMhVHS3rMKvznhT0a7R3lFlPdXqhlhHZG+/zpsVqNsMvQCZOdzLcVK
  artifact: NEvilES
  on:
    branch: master

notifications:
- provider: Email
  to:
  - craig@crgsoftware.com.au
  on_build_success: true
  on_build_failure: false
  on_build_status_changed: false